service: vacation-approval-service

provider:
  name: aws
  runtime: nodejs10.x

package:  
  include:
    - src/**
  exclude:
    - templates/**
    - processes/**
    - tables/**

plugins:
  - serverless-offline

functions:
  calculatedDaysOff:
    handler: src/handler.calculatedDaysOff
    events:
      - http: 
          path: daysoff
          method: get
